version: "3.9"
services:
  exb:
   image: cargr563/esri-exb:exb-1.4
   ports:
       - "3000:3000"
       - "3001:3001"
   volumes:
       - ./volumes/widgets:/home/node/ArcGISExperienceBuilder/client/your-extensions/widgets/
       - ./volumes/themes:/home/node/ArcGISExperienceBuilder/client/your-extensions/themes/
       - ./volumes/public:/home/node/ArcGISExperienceBuilder/server/public/
       - ./volumes/temp:/home/node/ArcGISExperienceBuilder/server/temp/
   command: npm start
       